### ISSUE TITLE
WAVE generator

### ISSUE THREAD

**Issue by picpic020960** [botofancalin/Odroid-Go-MultiApp#2]
bonjour
no wave generator in odroid-go multiapp version.
why ?
hardware limite ?
thank's for reply
Regards

**Comment by botofancalin** [comment]
Hi. I removed the signal generator because of the odd behavior of the hardware. I will take a look on it in the following days to see if i can make it work.

**Comment by botofancalin** [comment]
I added the signal generator on pin12. Is only square wave generator since the DAC pins are not broken out and they are both used by the audio amp/speaker. I also added the precompiled fw file.
Copy the fw file to sdcard then load it to GO.
